### ISSUE TITLE
Remove full-stop after temperature abbreviation

### ISSUE THREAD

**Issue by robinwhittleton** [mmastrac/h-beam-piper_four-day-planet#1]
https://github.com/mmastrac/h-beam-piper_four-day-planet/blob/f80197d697a571340209f9778bbc80e232da520a/src/epub/text/chapter-3.xhtml#L35

Temperature abbreviations don’t need full-stops (see https://standardebooks.org/manual/1.4.0/single-page#8.13.3.2).

**Comment by mmastrac** [comment]
Fixed, thanks!
