### ISSUE TITLE
Make book URL more specific

### ISSUE THREAD

**Issue by robinwhittleton** [mmastrac/h-beam-piper_four-day-planet#3]
https://github.com/mmastrac/h-beam-piper_four-day-planet/blob/f80197d697a571340209f9778bbc80e232da520a/src/epub/content.opf#L51

At the moment this is just pointing at H. Beam Piper’s wikipedia page. Can we make it more specific and point it at the Federation series subsection? (https://en.wikipedia.org/wiki/H._Beam_Piper#Federation_series).

**Comment by mmastrac** [comment]
Fixed, thank you
