### ISSUE TITLE
Combine selectors with the same rules

### ISSUE THREAD

**Issue by robinwhittleton** [mmastrac/h-beam-piper_four-day-planet#6]
https://github.com/mmastrac/h-beam-piper_four-day-planet/blob/e7ae4c3fd217d2b17c59d6de559de229957a0142/src/epub/css/local.css#L4-L10

Nit, but this should be:

```
abbr.temperature,
abbr.era{
	font-variant: all-small-caps;
}
```

**Comment by mmastrac** [comment]
Fixed, thanks again!
